import Link from 'next/link'
import { ScanLine } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link href="/" className="inline-flex items-center gap-2 mb-10">
          <div className="w-8 h-8 bg-gradient-to-br from-teal-500 to-teal-700 rounded-lg flex items-center justify-center">
            <ScanLine className="w-4 h-4 text-white" />
          </div>
          <span className="font-black text-slate-900">AutoAuditAI</span>
        </Link>

        <h1 className="text-3xl font-black text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-400 text-sm mb-10">Last updated: June 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using AutoAuditAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">2. Description of Service</h2>
            <p>AutoAuditAI provides AI-powered vehicle inspection reports using photographs and video recordings. The Service is intended for use by vehicle owners, rental businesses, dealerships, and individual car buyers and sellers worldwide.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">3. AI Inspection Disclaimer</h2>
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 text-sm">
              <p className="font-semibold text-amber-800 mb-2">Important: AI Limitations</p>
              <ul className="space-y-1.5 text-amber-700 list-disc list-inside">
                <li>AutoAuditAI reports are generated by artificial intelligence and are <strong>not a substitute for a physical inspection by a qualified mechanic or assessor.</strong></li>
                <li>AI detection accuracy depends on photo/video quality, lighting, angles, and vehicle condition. Some damage may be missed; some findings may be false positives.</li>
                <li>Repair cost estimates are approximate and based on regional market averages. Actual costs may vary significantly by location and repair shop.</li>
                <li>We do not guarantee the accuracy, completeness, or fitness for any legal purpose of any inspection report.</li>
                <li>Reports should be used as a screening tool and supporting documentation — not as the sole basis for financial or legal decisions.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">4. User Responsibilities</h2>
            <ul className="space-y-2 list-disc list-inside">
              <li>You must provide accurate information when registering and creating inspections.</li>
              <li>You must have the legal right to inspect the vehicle being photographed.</li>
              <li>You must not use the Service for fraudulent purposes or to misrepresent vehicle condition.</li>
              <li>You are responsible for the accuracy and legality of photos/videos you upload.</li>
              <li>You must not share your account credentials or allow unauthorised access.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">5. Subscriptions and Credits</h2>
            <p>The Service is offered on a credit-based subscription model. Credits expire at the end of each billing period unless otherwise stated. Free trial credits are limited to 3 inspections. We reserve the right to modify pricing with 30 days notice. No refunds are provided for unused credits except as required by law.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">6. Intellectual Property</h2>
            <p>You retain ownership of photos and videos you upload. By uploading, you grant AutoAuditAI a limited licence to process and analyse them to provide the Service. We do not sell or share your inspection data with third parties except as required by law.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by applicable law, AutoAuditAI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including any reliance on AI-generated inspection reports. Our total liability shall not exceed the amount you paid for the Service in the 30 days preceding any claim.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">8. Data and Privacy</h2>
            <p>Your use of the Service is also governed by our <Link href="/privacy" className="text-teal-600 hover:underline">Privacy Policy</Link>. You may request deletion of your account and data at any time by contacting us or using the account deletion feature in your settings.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">9. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify registered users by email. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3">10. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="tel:+923434994409" className="text-teal-600 hover:underline">+92-343-4994409</a> or via <a href="https://wa.me/923434994409" className="text-teal-600 hover:underline">WhatsApp</a>.</p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-slate-100 flex gap-6 text-sm text-slate-400">
          <Link href="/" className="hover:text-slate-600">← Back to home</Link>
          <Link href="/privacy" className="hover:text-slate-600">Privacy Policy</Link>
        </div>
      </div>
    </div>
  )
}
